#!/usr/bin/env node
/*
The MIT License (MIT)

Copyright (c) 2015 Kevin Phillips (kmp1)

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/

var fs = require('fs');
var constants = require('constants');
var wav = require("/Users/kevin/Projects/wav.js/master/src/wav.js");
var tzx = require("/Users/kevin/Projects/tzx.js/master/src/tzx.js");
var program = require('commander');
var path = require('path');
var pkg = require(path.join(__dirname, '../package.json'));

program
	.usage("[options] <file>")
    .version(pkg.version)
    .option('-o, --out <path>', 'Path to an output file (if not specified, a file in the same location with the same name ending with .wav will be created)')
    .option('-t, --type <1|2>', 'The type 1 is TZX and 2 is TAP - if not specified the file extension is used', parseInt)
    .option('-v, --verbose', 'Output verbose messages')
    .option('-l, --leftonly', 'Create a stereo audio file that has only one channel (probably the left) of sound')
    .parse(process.argv);

var input = program.args[0];

if (input === undefined) {
	console.log("No input file specified");
	return;
}

if (!fs.existsSync(input)) {
	console.log("Could not find the input file specified");
	return;
}

var output;
if (program.out == undefined) {
	output = input + ".wav";
} else {
	output = program.out;
}

var typeSpecified = false;
var isTzx;

if (program.type !== undefined) {
	if (program.type === 1) {
		isTzx = true;
		typeSpecified = true;
	} else if (program.type === 2) {
		isTzx = false;
		typeSpecified = true;
	} else {
		console.log("Invalid type '" + program.type + "' ignored the argument.");
	}
}

if (!typeSpecified) {

	var dot = input.lastIndexOf('.');
	if (dot === -1) {
		console.log("No extension on the input file and no expclit -t argument passed so assuming TZX");
		isTzx = true;
	} else {
		var extension = input.substr(dot + 1).trim().toLowerCase();
		if (extension === 'tzx') {
			isTzx = true;
		} else if (extension === 'tap') {
			isTzx = false;
		} else {
			console.log("Unrecognised extension on the input file and no expclit -t argument passed so assuming TZX");
			isTzx = true;
		}
	}
}

console.log("Converting " + input + " to " + output + " (as a " + (isTzx ? "tzx" : "tap") + " file)...");

var isLeftOnly = program.leftonly === undefined ? false : true;

var file = fs.readFileSync(input);
var inputFile = {
    getLength: function () { return file.length; },
    getByte: function (i) { return file[i]; }
};
var wave = wav.create(isLeftOnly ? 2 : 1, 44100, wav.SampleSize.EIGHT);
var details;
var blocks;

var splitFileCount = 0;

var outputWrapper = {
    addSample: function (s) {

        wave.addSample(s);
        if (isLeftOnly) {
            wave.addSample(0);
        }
    },
    getFrequency: wave.getFrequency,
    getSampleSize: wave.getSampleSize,
    stopTheTapeTrigger: function () {

        splitFileCount += 1;

        var newFile;
        if (output.lastIndexOf('.wav') !== -1) {
            newFile = output.substr(0, output.lastIndexOf('.')) + '_' + splitFileCount + '.wav';
        } else {
            newFile = output + '_' + splitFileCount;
        }

        fs.writeFileSync(newFile, new Buffer(wave.toByteArray()));

        wave = wav.create(isLeftOnly ? 2 : 1, 44100, wav.SampleSize.EIGHT);
    }
};

try {

    if (isTzx) {
        details = tzx.convertTzxToAudio(tzx.MachineSettings.ZXSpectrum48, inputFile, outputWrapper);
        blocks = details.blocks;
    } else {
        blocks = tzx.convertTapToAudio(tzx.MachineSettings.ZXSpectrum48, inputFile, outputWrapper);
        details = {};
    }

} catch (e) {
    console.log("CONVERSION FAILED:\n");
    console.log(e);
    return;
}

if (splitFileCount > 0) {
    splitFileCount += 1;
    if (output.lastIndexOf('.wav') !== -1) {
        output = output.substr(0, output.lastIndexOf('.')) + '_' + splitFileCount + '.wav';
    } else {
        output = output + '_' + splitFileCount;
    }
}
fs.writeFileSync(output, new Buffer(wave.toByteArray()));

console.log("Conversion SUCCESSFUL!");

if (program.verbose === undefined) {
    return;
}

if (details.version !== undefined) {
	console.log("ZXTape file revision " + details.version.major + "." + details.version.minor);
}

console.log("Number of Blocks: " + blocks.length);

for (var x = 1; x < blocks.length + 1; x += 1) {
    console.log();

    var block = blocks[x - 1];
    var logOutput = "";

    if (block.blockType === 0x10 || block.blockType === 0x11 || block.blockType === 0x14) {

        var headerText = "";

        if (block.programType !== undefined) {
	        if (block.programType === 0) {
	            headerText = "Program: " + block.headerText;
	        } else if (block.programType === 1) {
	            headerText = "Num. Array: " + block.headerText;
	        } else if (block.programType === 2) {
	            headerText = "Char. Array : " + block.headerText;
	        } else {
	            headerText = "Bytes: " + block.headerText;
	        }
    	}

    	var checkSum = "";
    	if (block.checkSum !== undefined) {
    		checkSum = "\n    CheckSum: 0x" + block.checkSum.toString(16) + " (" + block.checkSum + ") - ";

            if (block.checkSum === block.calculatedCheckSum) {
                checkSum += "OK";
            } else {
                checkSum += "INVALID, actual is: 0x" + block.calculatedCheckSum.toString(16) +
                    " (" + block.calculatedCheckSum + ")";
            }
    	}

    	var typeLabel;
    	if (block.blockType === 0x10) {
    		typeLabel = "0x10 - Standard Loading Data";
    	} else if (block.blockType === 0x11) {
    		typeLabel = "0x11 - Turbo Loading Data";
    	} else {
			typeLabel = "0x14 - Pure Data";
    	}

    	var flagLabel;
    	if (block.flag !== undefined) {
			flagLabel = "\n    Flag: 0x" + block.flag.toString(16) + " (" + block.flag + ")";
    	} else {
    		flagLabel = "";
    	}

    	var pauseLabel;
    	if (block.pause !== undefined) {
			pauseLabel = "\n    Pause after block: " + block.pause + " milliseconds";
    	} else {
    		pauseLabel = "";
    	}

        logOutput = typeLabel + " " + headerText + "\n    Length: " +
        	block.blockLength + " bytes " + flagLabel +
            checkSum + pauseLabel;

        if (block.blockType === 0x14) {
            logOutput += "\n    Bit 0 pulse: " + block.bit0Pulse + "\n    Bit 1 pulse: " + block.bit1Pulse +
                "\n    Last bit count: " + block.lastByteBitCount;
        }
    } else if (block.blockType === 0x12) {
    	logOutput = "0x12 - Pure tone\n    Pulse: " + block.pilotPulse + "\n    Pulse Length: " + block.pilotLength + ")";
    } else if (block.blockType === 0x21) {
    	logOutput = "0x21 - Group Start\n    Group Name: " + block.groupName;
    } else if (block.blockType === 0x24) {
    	logOutput = "0x24 - Loop\n    Count: " + block.loopCount;
    } else if (block.blockType === 0x25) {
    	logOutput = "0x25 - Loop End";
    } else if (block.blockType === 0x2a) {
    	logOutput = "0x2a - Stop the tape\n    Length: " +block.stopTapeLength
    } else if (block.blockType === 0x32) {
    	logOutput = "0x32 - Archive Info\n";
    	for (var y = 0; y < block.archiveInfo.length; y += 1) {
    		logOutput += "    " + block.archiveInfo[y].type + ": " + block.archiveInfo[y].info + "\n";
    	}
    } else if (block.blockType === 0x13) {
        logOutput = "0x13 - Sequence of Pulses\n    Pulse Count: " + block.pulseCount;
    } else if (block.blockType === 0x30) {
        logOutput = "0x30 - Description\n    Text: " + block.tapeDescription;
    }

    console.log("Block " + x + " (" + block.offset.toString(16) + "):  " + logOutput);
}
